services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app                  # Mount current directory to /app in container
      - mix_deps:/app/deps      # Store dependencies in a named volume for better performance
      - build_cache:/app/_build # Store build cache in a named volume for better performance
    # Don't use network_mode: host on Mac, as it behaves differently
    ports:
      - "4000:4000"  # Expose Phoenix port
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Point host.docker.internal to container gateway
    dns:
      - 8.8.8.8   # Google DNS
      - 1.1.1.1   # Cloudflare DNS
    environment:
      # Only keep Phoenix version as environment variable, since Erlang and Elixir are specified in Dockerfile
      # Use stable version of Phoenix
      - PHOENIX_VERSION=${PHOENIX_VERSION:-1.7.10}
      - DATABASE_HOST=host.docker.internal  # Point to Mac host
      - DATABASE_USER=${POSTGRES_USER:-postgres}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DATABASE_NAME=${POSTGRES_DB:-postgres}
      # Ensure file changes can be detected
      - WATCHDOG_ENABLED=true
    command: phx.server
    stdin_open: true
    tty: true
    user: "${CURRENT_UID:-1000}:${CURRENT_GID:-1000}"  # Use host user's UID/GID

volumes:
  mix_deps:     # Cache dependencies
  build_cache:  # Cache compilation results
